# setup @see https://help.github.com/en/articles/workflow-syntax-for-github-actions
# environment @see https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions
#                  https://help.github.com/en/articles/virtual-environments-for-github-actions
# example     @see https://github.com/actions/toolkit/blob/master/.github/workflows/workflow.yml
name: Release
# This workflow is triggered on pushes to the repository.
on: # @see https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  push:
    tags:
      - "*"

jobs:
  build: # job id, can be any string
    # Job name is Build And Publish
    name: Build And Publish
    # This job runs on Linux
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master # https://github.com/actions/actions
        with:
          lfs: false
      - name: Set up JDK 8.x
        uses: actions/setup-java@master # https://github.com/actions/setup-java
        with:
          version: "8.x" # The JDK version to make available on the path. Takes a whole or semver Jdk version, or 1.x syntax (e.g. 1.8 => Jdk 8.x)
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Build with Maven
        run: |
          cd tools;
          python3 gen_header_v2.py;
          python3 gen_header_v3.py;
          cd .. ;
          mvn package --file pom.xml
          if [[ -e "target/protocols.zip" ]]; then rm -f "target/protocols.zip"; fi
          if [[ -e "target/tools.zip" ]]; then rm -f "target/tools.zip"; fi
          echo $(cd header && zip -r "../target/protocols.zip" extensions *.proto *.pb)
          echo $(cd tools && zip -r "../target/tools.zip" requirements.txt extensions.pb *.py)
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "target/protocols.zip;target/tools.zip;target/*.jar"
          tags: true
          draft: true
          overwrite: true
